version: '3.8'

services:
    recommender:
        image: registry.heroku.com/recommend-games/web:latest
        container_name: bot-recommender
        environment:
            - DEBUG=0
            - PORT=8080
            - ADD_LOCAL_HOST=recommender,.local,localhost
        ports:
            - 9999:8080
        restart: unless-stopped

    mastodon:
        image: registry.gitlab.com/recommend.games/board-game-bot:latest
        container_name: bot-mastodon
        build: '.'
        command: [
            'python', '-m', 'board_game_bot.mastodon',
            '--base-url', 'http://recommender:8080',
            '--no-link',
            '--image-base-path', '/images'
        ]
        env_file: .env
        volumes:
            - '../board-game-scraper/images/full:/images'
        restart: unless-stopped
        stop_grace_period: 15m
        stop_signal: SIGINT
